/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionMissionRouteImport } from './routes/vision-mission'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TournamentRouteImport } from './routes/tournament'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RatedPlayersRouteImport } from './routes/rated-players'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MembersRouteImport } from './routes/members'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommitteeRouteImport } from './routes/committee'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminResourceRouteImport } from './routes/admin.$resource'

const VisionMissionRoute = VisionMissionRouteImport.update({
  id: '/vision-mission',
  path: '/vision-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentRoute = TournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RatedPlayersRoute = RatedPlayersRouteImport.update({
  id: '/rated-players',
  path: '/rated-players',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeRoute = CommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourceRoute = AdminResourceRouteImport.update({
  id: '/$resource',
  path: '/$resource',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/committee': typeof CommitteeRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/gallery': typeof GalleryRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRoute
  '/rated-players': typeof RatedPlayersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tournament': typeof TournamentRoute
  '/training': typeof TrainingRoute
  '/vision-mission': typeof VisionMissionRoute
  '/admin/$resource': typeof AdminResourceRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/committee': typeof CommitteeRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/gallery': typeof GalleryRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRoute
  '/rated-players': typeof RatedPlayersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tournament': typeof TournamentRoute
  '/training': typeof TrainingRoute
  '/vision-mission': typeof VisionMissionRoute
  '/admin/$resource': typeof AdminResourceRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/committee': typeof CommitteeRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/gallery': typeof GalleryRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRoute
  '/rated-players': typeof RatedPlayersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tournament': typeof TournamentRoute
  '/training': typeof TrainingRoute
  '/vision-mission': typeof VisionMissionRoute
  '/admin/$resource': typeof AdminResourceRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/auth'
    | '/committee'
    | '/contact'
    | '/downloads'
    | '/gallery'
    | '/members'
    | '/news'
    | '/rated-players'
    | '/reset-password'
    | '/tournament'
    | '/training'
    | '/vision-mission'
    | '/admin/$resource'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/auth'
    | '/committee'
    | '/contact'
    | '/downloads'
    | '/gallery'
    | '/members'
    | '/news'
    | '/rated-players'
    | '/reset-password'
    | '/tournament'
    | '/training'
    | '/vision-mission'
    | '/admin/$resource'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/auth'
    | '/committee'
    | '/contact'
    | '/downloads'
    | '/gallery'
    | '/members'
    | '/news'
    | '/rated-players'
    | '/reset-password'
    | '/tournament'
    | '/training'
    | '/vision-mission'
    | '/admin/$resource'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CommitteeRoute: typeof CommitteeRoute
  ContactRoute: typeof ContactRoute
  DownloadsRoute: typeof DownloadsRoute
  GalleryRoute: typeof GalleryRoute
  MembersRoute: typeof MembersRoute
  NewsRoute: typeof NewsRoute
  RatedPlayersRoute: typeof RatedPlayersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TournamentRoute: typeof TournamentRoute
  TrainingRoute: typeof TrainingRoute
  VisionMissionRoute: typeof VisionMissionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision-mission': {
      id: '/vision-mission'
      path: '/vision-mission'
      fullPath: '/vision-mission'
      preLoaderRoute: typeof VisionMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament': {
      id: '/tournament'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rated-players': {
      id: '/rated-players'
      path: '/rated-players'
      fullPath: '/rated-players'
      preLoaderRoute: typeof RatedPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee': {
      id: '/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof CommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$resource': {
      id: '/admin/$resource'
      path: '/$resource'
      fullPath: '/admin/$resource'
      preLoaderRoute: typeof AdminResourceRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminResourceRoute: typeof AdminResourceRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminResourceRoute: AdminResourceRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CommitteeRoute: CommitteeRoute,
  ContactRoute: ContactRoute,
  DownloadsRoute: DownloadsRoute,
  GalleryRoute: GalleryRoute,
  MembersRoute: MembersRoute,
  NewsRoute: NewsRoute,
  RatedPlayersRoute: RatedPlayersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TournamentRoute: TournamentRoute,
  TrainingRoute: TrainingRoute,
  VisionMissionRoute: VisionMissionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
